import Image from "next/image";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex">
      {children}
      <div className="relative h-screen flex-1/2">
        <Image
          src="/auth-img.jpg"
          alt="House where Facebook was built"
          fill
          className="object-cover"
        />
      </div>
    </div>
  );
}
