import Header from "@/components/general/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header />
      {children}
    </div>
  );
}
