import {
  HeartPulse,
  Brush,
  Eye,
  BookHeart,
  Accessibility,
  Plane,
  Baby,
  PiggyBank,
  LineChart,
  BadgeDollarSign,
  Clock,
  Laptop,
  GraduationCap,
  BookOpen,
  Bus,
  LucideHeartPulse,
  Dumbbell,
  PartyPopper,
  Shirt,
  HelpingHand,
  Cookie,
  Dog,
  Move3D,
  Tag,
  Hand,
  Brain,
  Medal,
  DollarSign,
  Monitor,
  BabyIcon,
} from "lucide-react";

export const jobBenefits = [
  { label: "Health insurance", icon: HeartPulse },
  { label: "Dental insurance", icon: Brush },
  { label: "Vision insurance", icon: Eye },
  { label: "Life insurance", icon: BookHeart },
  { label: "Disability insurance", icon: Accessibility },
  { label: "Paid time off (PTO)", icon: Plane },
  { label: "Parental leave", icon: Baby },
  { label: "Retirement plan (401k, pension, etc.)", icon: PiggyBank },
  { label: "Stock options or equity", icon: LineChart },
  { label: "Bonus opportunities", icon: BadgeDollarSign },
  { label: "Flexible working hours", icon: Clock },
  { label: "Remote work options", icon: Laptop },
  { label: "Professional development budget", icon: GraduationCap },
  { label: "Tuition reimbursement", icon: BookOpen },
  { label: "Commuter benefits", icon: Bus },
  { label: "Wellness programs", icon: LucideHeartPulse },
  { label: "Gym membership or fitness stipend", icon: Dumbbell },
  { label: "Company-sponsored events", icon: PartyPopper },
  { label: "Casual dress code", icon: Shirt },
  { label: "Employee assistance program (EAP)", icon: HelpingHand },
  { label: "Free snacks or meals", icon: Cookie },
  { label: "Pet-friendly office", icon: Dog },
  { label: "Relocation assistance", icon: Move3D },
  { label: "Employee discounts", icon: Tag },
  { label: "Volunteer time off", icon: Hand },
  { label: "Mental health support", icon: Brain },
  { label: "Performance bonuses", icon: Medal },
  { label: "Annual salary reviews", icon: DollarSign },
  { label: "Technology allowance", icon: Monitor },
  { label: "Childcare assistance", icon: BabyIcon },
];
